# Form implementation generated from reading ui file 'design/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWinWidgets(object):
    def setupUi(self, win):
        win.setObjectName("win")
        win.resize(637, 357)
        self.centralwidget = QtWidgets.QWidget(parent=win)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(120, -40, 421, 181))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel {\n"
"    color: \'#96be25\'\n"
"}")
        self.title.setObjectName("title")
        self.about = QtWidgets.QPushButton(parent=self.centralwidget)
        self.about.setGeometry(QtCore.QRect(10, 100, 301, 61))
        self.about.setObjectName("about")
        self.quick = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quick.setGeometry(QtCore.QRect(330, 100, 301, 61))
        self.quick.setObjectName("quick")
        self.path_to_pack = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.path_to_pack.setGeometry(QtCore.QRect(15, 180, 351, 41))
        self.path_to_pack.setText("")
        self.path_to_pack.setObjectName("path_to_pack")
        self.chose_path_to_file = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chose_path_to_file.setGeometry(QtCore.QRect(370, 185, 261, 32))
        self.chose_path_to_file.setObjectName("chose_path_to_file")
        self.path_to_unpack = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.path_to_unpack.setGeometry(QtCore.QRect(15, 230, 381, 41))
        self.path_to_unpack.setText("")
        self.path_to_unpack.setObjectName("path_to_unpack")
        self.chose_path_to_folder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chose_path_to_folder.setGeometry(QtCore.QRect(400, 235, 231, 32))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.chose_path_to_folder.setFont(font)
        self.chose_path_to_folder.setObjectName("chose_path_to_file_to_folder")
        self.create_arhive_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_arhive_btn.setGeometry(QtCore.QRect(10, 280, 371, 71))
        self.create_arhive_btn.setObjectName("create_arhive_btn")
        self.unpack_arhive_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.unpack_arhive_btn.setGeometry(QtCore.QRect(380, 280, 251, 71))
        self.unpack_arhive_btn.setObjectName("unpack_arhive_btn")
        win.setCentralWidget(self.centralwidget)

        self.retranslateUi(win)
        QtCore.QMetaObject.connectSlotsByName(win)

    def retranslateUi(self, win):
        _translate = QtCore.QCoreApplication.translate
        win.setWindowTitle(_translate("win", "Arihivator"))
        self.title.setText(_translate("win", "Arihivator"))
        self.about.setText(_translate("win", "Про Arihivator"))
        self.quick.setText(_translate("win", "Вийти"))
        self.path_to_pack.setPlaceholderText(_translate("win", "Введіть шлях до файлу/папки для СТВОРЕННЯ АРХІВА"))
        self.chose_path_to_file.setText(_translate("win", "Вибрати шлях до файлу..."))
        self.path_to_unpack.setPlaceholderText(_translate("win", "Введіть шлях до файлу/папки для РОЗПАКУВАННЯ АРХІВА"))
        self.chose_path_to_folder.setText(_translate("win", "Вибрати шлях до папки..."))
        self.create_arhive_btn.setText(_translate("win", "СТВОРИТИ АРХІВ"))
        self.unpack_arhive_btn.setText(_translate("win", "РОЗПАКУАВТИ АРХІВ"))
