# Form implementation generated from reading ui file 'design/about_win.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AboutWinWidgets(object):
    def setupUi(self, win):
        win.setObjectName("win")
        win.resize(426, 215)
        self.centralwidget = QtWidgets.QWidget(parent=win)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, -10, 421, 111))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel {\n"
"    color: \'#96be25\'\n"
"}")
        self.title.setObjectName("title")
        self.version = QtWidgets.QLabel(parent=self.centralwidget)
        self.version.setGeometry(QtCore.QRect(100, 90, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.version.setFont(font)
        self.version.setObjectName("version")
        self.open_code = QtWidgets.QLabel(parent=self.centralwidget)
        self.open_code.setGeometry(QtCore.QRect(20, 140, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.open_code.setFont(font)
        self.open_code.setObjectName("open_code")
        self.link = QtWidgets.QLabel(parent=self.centralwidget)
        self.link.setGeometry(QtCore.QRect(20, 170, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.link.setFont(font)
        self.link.setObjectName("link")
        win.setCentralWidget(self.centralwidget)

        self.retranslateUi(win)
        QtCore.QMetaObject.connectSlotsByName(win)

    def retranslateUi(self, win):
        _translate = QtCore.QCoreApplication.translate
        win.setWindowTitle(_translate("win", "Про Arihivator"))
        self.title.setText(_translate("win", "Arihivator"))
        self.version.setText(_translate("win", "Версія 1.0"))
        self.open_code.setText(_translate("win", "Вихідний код доступний на GitHub за посиланням:"))
        self.link.setText(_translate("win", "https://www.github.com/Andboogl/Arihivator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    win = QtWidgets.QMainWindow()
    ui = AboutWinWidgets()
    ui.setupUi(win)
    win.show()
    sys.exit(app.exec())
